version: '3'
services:

### Workspace Utilities ##################################
  workspace:
    image: 620139381534.dkr.ecr.us-east-1.amazonaws.com/abrigham/workspace:latest
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
    links:
      - docker-in-docker

### PHP-FPM ##############################################
  php-fpm:
    image: 620139381534.dkr.ecr.us-east-1.amazonaws.com/abrigham/php-fpm:latest
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - FAKETIME=${PHP_FPM_FAKETIME}
    links:
      - workspace
      - docker-in-docker

### NGINX Server #########################################
  nginx:
    image: 620139381534.dkr.ecr.us-east-1.amazonaws.com/abrigham/nginx:latest
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    links:
      - php-fpm
      - anaconda

### Docker-in-Docker ################################################
  docker-in-docker:
    image: 620139381534.dkr.ecr.us-east-1.amazonaws.com/abrigham/docker-in-docker:latest
    privileged: true

### ANACONDA ################################################
  anaconda:
    image: 620139381534.dkr.ecr.us-east-1.amazonaws.com/abrigham/anaconda:latest